server:
  error:
    include-stacktrace: always

spring:

  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/altium-components
    username: postgres
    password: postgres

logging:
  config: classpath:logging/log4j-dev.yaml