name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        cache: 'gradle'
            
    - name: Run Integration Tests
      run: gradle clean build --info
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build docker image
      run: gradle bootBuildImage --info
      
    - name: Tag docker image
      run: docker tag altium-migrator ${{ secrets.DOCKERHUB_USERNAME }}/altium-migrator:latest
      
    - name: Push docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/altium-migrator:latest
